### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by gossi** [rajasegar/ember-gen-uml#7]
Hey,

I just finished a task on class diagramm two packages of our app (manually) to PlantUML, would've loved some automation here. Our code is written in Typescript (I tried https://github.com/bafolts/tplant) but the results weren't usable.

Any plans to support TS here or a way to integrate something like that?

**Comment by rajasegar** [comment]
@gossi Yes I do have one

**Comment by rajasegar** [comment]
@gossi Came up with a minimal version for TS support, please check and let me know for any issues. You need to pass `--ts` option with the cli for Typescript
